blank_issues_enabled: false
contact_links:
  - name: Get touch privately here
    url: https://mailto:gulybyte@gmail.com
    about: Report a sensitive issue that cannot go public privately with the project maintainer.
