volumes:
  todo-api-volume-postgres:

networks:
  todo-api-network:
    driver: bridge

services:
  postgres:
    image: 'postgres:16.1-alpine'
    environment:
      - 'POSTGRES_DB=todo-api'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '15432:5432'
    networks:
      - todo-api-network
    volumes:
      - todo-api-volume-postgres:/var/lib/postgresql/data
