name: Java CI with Gradle

on:
  push:
    paths:
      - 'todo-api/**'
    branches:
      - 'master'
      - 'releases/**'
      - '!releases/**-no-verify'
      - '!**-no-verify'
  pull_request:
    paths:
        - 'todo-api/**'
    branches:
      - 'master'
      - 'releases/**'
      - '!releases/**-no-verify'
      - '!**-no-verify'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@2
      with:
       cache-disabled: true
       gradle-version: 8.1
       arguments: build
       build-root-directory: todo-api
